project:
  type: website
  output-dir: docs

website:
  title: "Ning Yan"

  navbar:
    pinned: true
    search: true

    left:
      - href: mathematics/index.qmd
        text: "数学机理"
      - href: deep-learning/index.qmd
        text: "深度学习模型"
      - href: code/index.qmd
        text: "代码实战"
      - href: llm/index.qmd
        text: "LLM学习"
      - href: about.qmd
        text: "关于"

    right:
      - icon: github
        href: "https://github.com/N1ngYan2004726"
      - icon: circle-half
        id: theme-toggle
        href: "#"
        text: ""
        aria-label: "切换主题"


  page-footer:
    left: "Ning Yan"
    right: "个人学习笔记"

format:
  html:
    lang: zh-CN

    theme: cosmo
    css: styles.css
    
    include-after-body:
      - assets/theme-toggle.html
      - assets/category-enhancer.html

    toc: false

    smooth-scroll: true

    code-copy: true
    code-overflow: wrap

    html-math-method: katex

execute:
  freeze: auto